package rs.ac.uns.ftn.xml.team17.authservice.service.entityservice;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import rs.ac.uns.ftn.xml.team17.authservice.model.entity.user.User;
import rs.ac.uns.ftn.xml.team17.authservice.repository.UserRepository;

@Service
public class UserService {
	@Autowired
	private UserRepository userRepository;

	/**
	 * Tries to find user with passed username. If no user is found causes
	 * UsernameNotFoundException.
	 * 
	 * @param username
	 * @throws UsernameNotFoundException
	 * @return
	 */
	public User findByUsername(String username) throws UsernameNotFoundException {
		Optional<User> user = userRepository.findByUsername(username);
		if (!user.isPresent()) {
			throw new UsernameNotFoundException("Username " + username + " noy found.");
		}
		return user.get();
	}

	/**
	 * Saves user to datebase. Id is autogenerated.
	 * 
	 * @param user
	 * @return saved user with id set
	 */
	public User saveUser(User user) {
		return userRepository.save(user);
	}
}
