package rs.ac.uns.ftn.xml.team17.authservice.service.entityservice;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import rs.ac.uns.ftn.xml.team17.authservice.dto.customer.CustomerDTO;
import rs.ac.uns.ftn.xml.team17.authservice.model.entity.user.Customer;
import rs.ac.uns.ftn.xml.team17.authservice.model.entity.user.User;
import rs.ac.uns.ftn.xml.team17.authservice.repository.UserRepository;

@Service
public class UserService {
	@Autowired
	private UserRepository userRepository;

	/**
	 * Tries to find user with passed username. If no user is found causes
	 * UsernameNotFoundException.
	 * 
	 * @param username
	 * @throws UsernameNotFoundException
	 * @return
	 */
	public User findByUsername(String username) throws UsernameNotFoundException {
		Optional<User> user = userRepository.findByUsername(username);
		if (!user.isPresent()) {
			throw new UsernameNotFoundException("Username " + username + " noy found.");
		}
		return user.get();
	}

	/**
	 * Saves user to datebase. Id is autogenerated.
	 * 
	 * @param user
	 * @return saved user with id set
	 */
	public User saveUser(User user) {
		return userRepository.save(user);
	}
	
	/**
	 * Blocks the existing customer. Checks if the user is a customer
	 * and has been previously blocked.
	 * 
	 * @param id - id of the customer
	 */
	public void blockCustomer(Integer id) {
		Optional <User> user = userRepository.findById(id);
		if(!user.isPresent()) { 
			// TODO: exception
		}
		
		if(!(user.get() instanceof Customer)) {
			// TODO: exception
		}
		
		if(user.get().getBlocked()) { // TODO: proveriti uslov
			// TODO: exception
			System.out.println("vec je blokiran, ne mozete ga opet blokirati.");
		}
		user.get().setBlocked(true);	
		
		userRepository.save(user.get());
	}

	/**
	 * Activates the blocked customer. Checks if the user is a customer
	 * and has been previously blocked.
	 * 
	 * @param id - id of the customer
	 */
	public void activateCustomer(Integer id) {
		Optional <User> user = userRepository.findById(id);
		if(!user.isPresent()) { 
			// TODO: exception
		}
		
		if(!(user.get() instanceof Customer)) {
			// TODO: exception
		}
		
		if(!user.get().getBlocked()) { // TODO: proveriti uslov
			// TODO: exception
			System.out.println("nije blokiran, pa se ne moze blokirati");
		}
		user.get().setBlocked(false);
		userRepository.save(user.get());
	}

	/**
	 * Removes the active customer. Checks if the user is a customer.
	 * 
	 * @param id - id of the customer
	 */
	public void removeCustomer(Integer id) {
		// TODO Auto-generated method stub
		Optional <User> user = userRepository.findById(id);
		if(!user.isPresent()) { 
			// TODO: exception
		}
		
		if(!(user.get() instanceof Customer)) {
			// TODO: exception
		}
		
		user.get().setActive(false);
		user.get().setUsername(null); // TODO: ispraviti
		
		userRepository.save(user.get());
	}
	
	/**
	 * Converts user to customer DTO.
	 * 
	 * @return informations about all customers
	 */
	public List<CustomerDTO> getCustomers() {
		Iterable<User> users = userRepository.findAll();
		
		// convert services to DTO
		List<CustomerDTO> ret = new ArrayList<>();
		for(User user: users) {
			if(user instanceof Customer) {
				ret.add(new CustomerDTO(user));
			}
		}
		return ret;		
	}
}
