//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 03:38:42 PM CEST 
//


package rs.ac.uns.ftn.xml.team17.adminservice.dto.soap.RoomType;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roomType"
})
@XmlRootElement(name = "getRoomTypesResponse")
@Setter
@Getter
public class GetRoomTypesResponse {

    @XmlElement(name = "RoomType", required = true)
    protected List<GetRoomTypesResponse.RoomType> roomType;

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "active"
    })
    @NoArgsConstructor
    @Getter
    @Setter
    public static class RoomType {

        protected int id;
        @XmlElement(required = true)
        protected String name;
        protected boolean active;
        
        public RoomType( rs.ac.uns.ftn.xml.team17.adminservice.model.roomType.RoomType r) {
        	this.id = r.getId();
        	this.name = r.getName();
        	this.active = r.getActive();
        }
        
    }

}
