//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 12:22:43 PM CEST 
//


package rs.ac.uns.ftn.xml.team17.roomservice.dto.soap.price;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml.team17.setprice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml.team17.setprice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetPriceResponse }
     * 
     */
    public SetPriceResponse createSetPriceResponse() {
        return new SetPriceResponse();
    }

    /**
     * Create an instance of {@link SetPriceRequest }
     * 
     */
    public SetPriceRequest createSetPriceRequest() {
        return new SetPriceRequest();
    }

}
