//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 12:22:43 PM CEST 
//


package rs.ac.uns.ftn.xml.team17.roomservice.dto.soap.price;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "dateTo",
    "dateFrom",
    "price"
})

@NoArgsConstructor
@Getter
@Setter
@XmlRootElement(name = "setPriceRequest")
public class SetPriceRequest {

    protected int id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date dateTo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date dateFrom;
    protected double price;

}
