//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 05:06:03 PM CEST 
//


package rs.ac.uns.ftn.xml.team17.adminservice.dto.soap.RoomCategory;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "roomCategory"
})
@XmlRootElement(name = "getRoomCategoriesResponse")
@Setter
@Getter
public class GetRoomCategoriesResponse {

    @XmlElement(name = "RoomCategory", required = true)
    protected List<GetRoomCategoriesResponse.RoomCategory> roomCategory;

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "numberOfStars",
        "description",
        "active"
    })
    
    @NoArgsConstructor
    @Getter
    @Setter
    public static class RoomCategory {

        protected int id;
        protected int numberOfStars;
        @XmlElement(required = true)
        protected String description;
        protected boolean active;

        public RoomCategory(rs.ac.uns.ftn.xml.team17.adminservice.model.roomCategory.RoomCategory r) {
        	this.id = r.getId();
        	this.numberOfStars = r.getNumberOfStars();
        	this.description = r.getDescription();
        	this.active = r.getActive();
        }
    }

}
