//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 10:24:05 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.team17.xml.ftn.uns.ac.rs/GetReservations", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.ac.uns.ftn.xml.team17.reservationsservice.dto.soap.getreservations;
