//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 10:24:05 AM CEST 
//

package rs.ac.uns.ftn.xml.team17.reservationsservice.dto.soap.getreservations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import lombok.NoArgsConstructor;

/**
 * <p>
 * Java class for Reservation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Reservation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dateFrom" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dateTo" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="totalPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="status" type="{http://www.team17.xml.ftn.uns.ac.rs/GetReservations}ReservationStatus"/>
 *         &lt;element name="user" type="{http://www.team17.xml.ftn.uns.ac.rs/GetReservations}User"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation", propOrder = { "id","roomId", "dateFrom", "dateTo", "totalPrice", "status", "user" })
@NoArgsConstructor
public class Reservation {

	protected int id;
	
	protected int roomId;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected String dateFrom;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected String dateTo;
	protected double totalPrice;
	@XmlElement(required = true)
	protected ReservationStatus status;
	@XmlElement(required = true)
	protected User user;

	public Reservation(rs.ac.uns.ftn.xml.team17.reservationsservice.model.reservation.Reservation r) {
		this.id = r.getId();
		
		this.roomId = r.getDayReservations().get(0).getReservation().getRoom().getId();
		
		String tmp0 = r.getDayReservations().get(0).getDate().toString();
		String[] splited0 = tmp0.split(" ");
		System.out.println(splited0[0]);
		this.dateFrom = splited0[0];
		String tmp1 = r.getDayReservations().get(r.getDayReservations().size()-1).getDate().toString();
		String[] splited1 = tmp1.split(" ");
		System.out.println(splited1[0]);
		this.dateTo = splited1[0];
		this.totalPrice = r.getTotal();
		if (r.getStatus() == rs.ac.uns.ftn.xml.team17.reservationsservice.model.reservation.Reservation.ReservationStatus.RESERVED) {
			this.status = ReservationStatus.RESERVED;
		}
		if (r.getStatus() == rs.ac.uns.ftn.xml.team17.reservationsservice.model.reservation.Reservation.ReservationStatus.CANCELED) {
			this.status = ReservationStatus.CANCELED;
		}
		if (r.getStatus() == rs.ac.uns.ftn.xml.team17.reservationsservice.model.reservation.Reservation.ReservationStatus.HAPPENED) {
			this.status = ReservationStatus.HAPPENED;
		}
		if(r.getCustomer() != null) {
			this.user = new User(r.getCustomer());
		}
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(int value) {
		this.id = value;
	}

	
	
	
	/**
	 * Gets the value of the dateFrom property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public String getDateFrom() {
		return dateFrom;
	}

	/**
	 * Sets the value of the dateFrom property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDateFrom(String value) {
		this.dateFrom = value;
	}

	/**
	 * Gets the value of the dateTo property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public String getDateTo() {
		return dateTo;
	}

	/**
	 * Sets the value of the dateTo property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDateTo(String value) {
		this.dateTo = value;
	}

	/**
	 * Gets the value of the totalPrice property.
	 * 
	 */
	public double getTotalPrice() {
		return totalPrice;
	}

	/**
	 * Sets the value of the totalPrice property.
	 * 
	 */
	public void setTotalPrice(double value) {
		this.totalPrice = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return possible object is {@link ReservationStatus }
	 * 
	 */
	public ReservationStatus getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value allowed object is {@link ReservationStatus }
	 * 
	 */
	public void setStatus(ReservationStatus value) {
		this.status = value;
	}

	/**
	 * Gets the value of the user property.
	 * 
	 * @return possible object is {@link User }
	 * 
	 */
	public User getUser() {
		return user;
	}

	/**
	 * Sets the value of the user property.
	 * 
	 * @param value allowed object is {@link User }
	 * 
	 */
	public void setUser(User value) {
		this.user = value;
	}

	public int getRoomId() {
		return roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

}
