//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 05:23:46 PM CEST 
//


package rs.ac.uns.ftn.xml.team17.reservationsservice.model.recension;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import rs.ac.uns.ftn.xml.team17.reservationsservice.model.reservation.Reservation;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Recension", namespace = "http://www.tim17.com/recension", propOrder = {
    "id",
    "isApproved",
    "dateOfRecension",
    "rating",
    "comment"
})
//Lambok annotations
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Recension {

	@EqualsAndHashCode.Include	
	@XmlElement(namespace = "http://www.tim17.com/recension")
    protected Integer id;
	
    @XmlElement(namespace = "http://www.tim17.com/recension", defaultValue = "false")
    protected Boolean isApproved;
      
    @XmlElement(namespace = "http://www.tim17.com/recension")
    protected Double rating;
 
    @XmlElement(namespace = "http://www.tim17.com/recension")
    protected String comment;
   
	@XmlElement(namespace = "http://www.tim17.com/recension", required = true)
	protected Reservation reservation;
   
	@XmlElement(namespace = "http://www.tim17.com/recension", required = true)
	@XmlSchemaType(name = "dateTime")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern="yyyy-MM-dd")
	protected Date creationDate;
	
	protected Date modificationDate;

}
