//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.15 at 05:34:41 PM CEST 
//


package rs.ac.uns.ftn.xml.team17.reservationsservice.dto.soap.newmessage;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import lombok.NoArgsConstructor;


/**
 * <p>Java class for Message complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reservationId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dateSent" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="status" type="{http://www.team17.xml.ftn.uns.ac.rs/NewMessage}MessageDirection"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Message", propOrder = {
    "reservationId",
    "id",
    "dateSent",
    "status",
    "message"
})
@NoArgsConstructor
public class Message {

    protected int reservationId;
    protected int id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date dateSent;
    @XmlElement(required = true)
    protected MessageDirection status;
    @XmlElement(required = true)
    protected String message;

    public Message(rs.ac.uns.ftn.xml.team17.reservationsservice.model.message.Message m) {
		this.reservationId = m.getReservation().getId();
		this.id = m.getId();
		this.dateSent = m.getCreationDate();
		if(m.getStatus() == rs.ac.uns.ftn.xml.team17.reservationsservice.model.message.MessageDirection.TO_AGENT) {
			this.status = MessageDirection.TO_AGENT;
		}
		if(m.getStatus() == rs.ac.uns.ftn.xml.team17.reservationsservice.model.message.MessageDirection.TO_CUSTOMER) {
			this.status = MessageDirection.TO_CUSOTOMER;
		}
		this.message = m.getMessage();
	}

	/**
     * Gets the value of the reservationId property.
     * 
     */
    public int getReservationId() {
        return reservationId;
    }

    /**
     * Sets the value of the reservationId property.
     * 
     */
    public void setReservationId(int value) {
        this.reservationId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the dateSent property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDateSent() {
        return dateSent;
    }

    /**
     * Sets the value of the dateSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSent(Date value) {
        this.dateSent = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDirection }
     *     
     */
    public MessageDirection getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDirection }
     *     
     */
    public void setStatus(MessageDirection value) {
        this.status = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
