//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 09:57:12 AM CEST 
//


package rs.ac.uns.ftn.xml.team17.roomservice.dto.soap.room;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import lombok.NoArgsConstructor;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoomCategory", propOrder = {
    "id",
    "numberOfStars",
    "description"
})
@NoArgsConstructor
public class RoomCategory {

    protected int id;
    protected int numberOfStars;
    protected String description;

    public RoomCategory(rs.ac.uns.ftn.xml.team17.roomservice.model.roomCategory.RoomCategory category) {
		this.id = category.getId();
		this.numberOfStars = category.getNumberOfStars();
		this.description = category.getDescription();
	}

	/**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the numberOfStars property.
     * 
     */
    public int getNumberOfStars() {
        return numberOfStars;
    }

    /**
     * Sets the value of the numberOfStars property.
     * 
     */
    public void setNumberOfStars(int value) {
        this.numberOfStars = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
