//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 09:57:12 AM CEST 
//


package rs.ac.uns.ftn.xml.team17.roomservice.dto.soap.room;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import lombok.NoArgsConstructor;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Room", propOrder = {
    "hotelId",
    "address",
    "type",
    "category",
    "defaultPrice",
    "numberOfPeople",
    "cancelationDays",
    "additionalServices",
    "description",
    "totalRating",
    "numberOfRatings",
    "roomNumber"
})
@NoArgsConstructor
public class Room {

    protected int hotelId;
    @XmlElement(required = true)
    protected Address address;
    @XmlElement(required = true)
    protected RoomType type;
    @XmlElement(required = true)
    protected RoomCategory category;
    protected double defaultPrice;
    protected int numberOfPeople;
    protected int cancelationDays;
    protected List<AdditionalService> additionalServices;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(defaultValue = "0")
    protected double totalRating;
    @XmlElement(defaultValue = "0")
    protected int numberOfRatings;
    protected Integer roomNumber;
    
    public Room(rs.ac.uns.ftn.xml.team17.roomservice.model.room.Room r) {
    	this.hotelId = r.getHotel().getId();
    	this.address = new rs.ac.uns.ftn.xml.team17.roomservice.dto.soap.room.Address(r.getAddress());
    	this.type = new rs.ac.uns.ftn.xml.team17.roomservice.dto.soap.room.RoomType(r.getType());
    	this.category = new rs.ac.uns.ftn.xml.team17.roomservice.dto.soap.room.RoomCategory(r.getCategory());
    	this.defaultPrice = r.getDefaultPrice();
    	this.numberOfPeople = r.getNumberOfPeople();
    	this.cancelationDays = r.getCancelationDays();
    	if(r.getAdditionalServices() != null) {
    		for(rs.ac.uns.ftn.xml.team17.roomservice.model.additionalService.AdditionalService a : r.getAdditionalServices()) {
        		AdditionalService as = new AdditionalService(a);
        		this.additionalServices.add(as);
        	}
    	}
    	this.description = r.getDescription();
    	this.totalRating = r.getTotalRating();
    	this.numberOfPeople = r.getNumberOfRatings();
    	this.roomNumber = r.getRoomNumber();
    }

    /**
     * Gets the value of the hotelId property.
     * 
     */
    public int getHotelId() {
        return hotelId;
    }

    /**
     * Sets the value of the hotelId property.
     * 
     */
    public void setHotelId(int value) {
        this.hotelId = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RoomType }
     *     
     */
    public RoomType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomType }
     *     
     */
    public void setType(RoomType value) {
        this.type = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link RoomCategory }
     *     
     */
    public RoomCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomCategory }
     *     
     */
    public void setCategory(RoomCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the defaultPrice property.
     * 
     */
    public double getDefaultPrice() {
        return defaultPrice;
    }

    /**
     * Sets the value of the defaultPrice property.
     * 
     */
    public void setDefaultPrice(double value) {
        this.defaultPrice = value;
    }

    /**
     * Gets the value of the numberOfPeople property.
     * 
     */
    public int getNumberOfPeople() {
        return numberOfPeople;
    }

    /**
     * Sets the value of the numberOfPeople property.
     * 
     */
    public void setNumberOfPeople(int value) {
        this.numberOfPeople = value;
    }

    /**
     * Gets the value of the cancelationDays property.
     * 
     */
    public int getCancelationDays() {
        return cancelationDays;
    }

    /**
     * Sets the value of the cancelationDays property.
     * 
     */
    public void setCancelationDays(int value) {
        this.cancelationDays = value;
    }

    /**
     * Gets the value of the additionalServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalService }
     * 
     * 
     */
    public List<AdditionalService> getAdditionalServices() {
        if (additionalServices == null) {
            additionalServices = new ArrayList<AdditionalService>();
        }
        return this.additionalServices;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the totalRating property.
     * 
     */
    public double getTotalRating() {
        return totalRating;
    }

    /**
     * Sets the value of the totalRating property.
     * 
     */
    public void setTotalRating(double value) {
        this.totalRating = value;
    }

    /**
     * Gets the value of the numberOfRatings property.
     * 
     */
    public int getNumberOfRatings() {
        return numberOfRatings;
    }

    /**
     * Sets the value of the numberOfRatings property.
     * 
     */
    public void setNumberOfRatings(int value) {
        this.numberOfRatings = value;
    }

    /**
     * Gets the value of the roomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRoomNumber() {
        return roomNumber;
    }

    /**
     * Sets the value of the roomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRoomNumber(Integer value) {
        this.roomNumber = value;
    }

    
    
    
}
