# Generated by Django 2.2 on 2019-04-26 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('postal_code', models.CharField(default='', max_length=30)),
                ('street', models.CharField(default='', max_length=30)),
                ('street_number', models.CharField(default='', max_length=30)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib', models.CharField(default='', max_length=30)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Address')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('description', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('default_price', models.FloatField()),
                ('number_of_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cancelation_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(default='', max_length=256)),
                ('number_of_raitings', models.IntegerField()),
                ('additional_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.AdditionalService')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Address')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Hotel')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.RoomCategory')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='Resrvation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reservation', models.DateField()),
                ('has_happend', models.BooleanField(default=False)),
                ('customer_id', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Room')),
            ],
        ),
        migrations.CreateModel(
            name='DayResrvation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Resrvation')),
            ],
        ),
    ]
