# Generated by Django 2.2.1 on 2019-05-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='additional_service',
        ),
        migrations.AddField(
            model_name='room',
            name='additional_service',
            field=models.ManyToManyField(to='agentski_modul.AdditionalService'),
        ),
    ]
