# Generated by Django 2.2.2 on 2019-06-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0003_auto_20190610_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcategory',
            old_name='number_of_stars',
            new_name='numberOfStars',
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
