# Generated by Django 2.2.2 on 2019-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0004_auto_20190611_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
