# Generated by Django 2.2.2 on 2019-06-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0005_auto_20190611_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_number',
            new_name='streetNumber',
        ),
    ]
