# Generated by Django 2.2.2 on 2019-06-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0006_auto_20190611_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='additional_service',
            new_name='additionalService',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='cancelation_days',
            new_name='cancelationDays',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='default_price',
            new_name='defaultPrice',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number_of_people',
            new_name='numberOfPeople',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number_of_raitings',
            new_name='numberOfRaitings',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_category',
            new_name='roomCategory',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='roomNumber',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='roomType',
        ),
    ]
