# Generated by Django 2.2.2 on 2019-06-13 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0008_auto_20190612_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='totalRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='cancelationDays',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='numberOfRaitings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agentski_modul.RoomCategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agentski_modul.RoomType'),
        ),
    ]
