# Generated by Django 2.2.2 on 2019-06-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0009_auto_20190613_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resrvation',
            old_name='date_of_reservation',
            new_name='dateOfReservation',
        ),
        migrations.RemoveField(
            model_name='resrvation',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='resrvation',
            name='has_happend',
        ),
        migrations.AddField(
            model_name='resrvation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agentski_modul.Customer'),
        ),
        migrations.AddField(
            model_name='resrvation',
            name='status',
            field=models.CharField(choices=[('R', 'RESERVED'), ('H', 'HAPPENED'), ('C', 'CANCELED')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='resrvation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resrvation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentski_modul.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentski_modul.RoomCategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agentski_modul.RoomType'),
        ),
    ]
