# Generated by Django 2.2.2 on 2019-06-13 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0010_auto_20190613_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='resrvation',
            name='dateFrom',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resrvation',
            name='dateTo',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
