# Generated by Django 2.2.2 on 2019-06-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0011_auto_20190613_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resrvation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agentski_modul.Customer'),
        ),
    ]
