# Generated by Django 2.2.2 on 2019-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0012_auto_20190613_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resrvation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'RESERVED'), ('HAPPENED', 'HAPPENED'), ('CANCELED', 'CANCELED')], default='R', max_length=8),
        ),
    ]
