# Generated by Django 2.2.2 on 2019-06-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0014_auto_20190613_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='pib',
            new_name='PIB',
        ),
    ]
