# Generated by Django 2.2.2 on 2019-06-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0015_auto_20190615_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomFloor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
