# Generated by Django 2.2.2 on 2019-06-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0016_room_roomfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField()),
                ('photo', models.FileField(upload_to='images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Room')),
            ],
        ),
    ]
