# Generated by Django 2.2.2 on 2019-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0017_roomfotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resrvation',
            name='dateOfReservation',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='dsad', max_length=32),
            preserve_default=False,
        ),
    ]
