# Generated by Django 2.2.2 on 2019-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0018_auto_20190621_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='resrvation',
            name='totalPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
