# Generated by Django 2.2.2 on 2019-06-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0019_resrvation_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resrvation',
            old_name='room',
            new_name='roomId',
        ),
    ]
