# Generated by Django 2.2.2 on 2019-06-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0020_auto_20190621_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='dateSent',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('TO_CUSTOMER', 'TO_CUSTOMER'), ('TO_AGENT', 'TO_AGENT')], default='TO_AGENT', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resrvation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'RESERVED'), ('HAPPENED', 'HAPPENED'), ('CANCELED', 'CANCELED')], max_length=8),
        ),
    ]
