# Generated by Django 2.2.2 on 2019-06-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0022_message_reservationid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recension',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('isApproved', models.BooleanField()),
                ('reservationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Resrvation')),
            ],
        ),
    ]
