# Generated by Django 2.2.2 on 2019-06-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0023_recension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_token', models.CharField(max_length=512)),
            ],
        ),
    ]
