# Generated by Django 2.2.2 on 2019-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0024_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
