# Generated by Django 2.2.2 on 2019-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0025_auto_20190627_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
