# Generated by Django 2.2.2 on 2019-06-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0026_auto_20190627_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agentski_modul.Address'),
        ),
    ]
