# Generated by Django 2.2.2 on 2019-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0027_auto_20190627_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='numberOfRaitings',
            field=models.IntegerField(null=True),
        ),
    ]
