# Generated by Django 2.2.2 on 2019-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0028_auto_20190627_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='numberOfRaitings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='totalRating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
