# Generated by Django 2.2.2 on 2019-06-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0029_auto_20190627_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
