# Generated by Django 2.2.2 on 2019-06-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0030_auto_20190627_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recension',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
