# Generated by Django 2.2.2 on 2019-06-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0032_auto_20190629_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='numberOfRaitings',
        ),
        migrations.RemoveField(
            model_name='room',
            name='totalRating',
        ),
        migrations.AlterField(
            model_name='room',
            name='additionalService',
            field=models.ManyToManyField(blank=True, null=True, to='agentski_modul.AdditionalService'),
        ),
    ]
