# Generated by Django 2.2.2 on 2019-06-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0033_auto_20190629_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='recension',
            name='title',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='recension',
            name='username',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='recension',
            name='comment',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='room',
            name='additionalService',
            field=models.ManyToManyField(blank=True, to='agentski_modul.AdditionalService'),
        ),
    ]
