# Generated by Django 2.2.2 on 2019-06-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentski_modul', '0034_auto_20190629_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
