hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
    ConnectTimeout: 10000
    ReadTimeout: 10000