//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.25 at 04:24:33 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.team17.xml.ftn.uns.ac.rs/authentication", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.ac.uns.ftn.xml.team17.authservice.dto.authentication;